### ISSUE TITLE
Warning: Task "contrib-jade" failed

### ISSUE THREAD

**Issue by 7wonders** [AdesisNetlife/grunt-jade-i18n#23]
```
Running tasks: jade

Running "jade" task

Running "jade:templates" (jade) task
Verifying property jade.templates exists in config...OK
Files: src/index.jade -> out/index.html
Options: i18n={"locales":"locales/*.json","namespace":"$i18n"}, pretty

Running "contrib-jade" task
>> No "contrib-jade" targets found.
Warning: Task "contrib-jade" failed. Use --force to continue.

Aborted due to warnings.
```

Happens when running 'grunt jade' with the default settings as per the example.

**Comment by 7wonders** [comment]
Im running node v0.10.36 and grunt 0.4.5 if that helps. Please let me know what I can do to help debug. I have exhausted my limited knowledge.

**Comment by h2non** [comment]
I've fixed this error. This is caused when running multiple tasks in Grunt, since the tasks tries to discover those tasks to avoid possible conflicts.

I've just released a new fresh `0.3.4` version that fixes this issue.
```bash
npm update grunt-jade-i18n
```

I'm sorry for the troubles, and thank you for reporting the issue

**Comment by 7wonders** [comment]
I got all excited but sadly its still not working :(

From npm test
```
> grunt test

Running "clean:0" (clean) task

Running "clean:1" (clean) task

Running "clean:2" (clean) task

Running "coffeelint:tasks" (coffeelint) task

tasks/i18n.coffee
  ⚠  line 100  Line ends with trailing whitespace

⚠ 1 warning


Running "coffeelint:test" (coffeelint) task
>> 0 files lint free.

Running "coffeelint:grunt" (coffeelint) task
>> 1 file lint free.

Running "jade:translateDir" (jade) task
>> No "contrib-jade" targets found.
Warning: Task "contrib-jade" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
```

And from the task

```
Running "jade:templates" (jade) task
>> No "contrib-jade" targets found.
Warning: Task "contrib-jade" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by h2non** [comment]
That's just a warning form `coffeelint` task. I removed the trailing whitespace.

By the way, I created a fresh repository with the example Gruntfile configuration and all is working fine.

You can check also the Travis build: https://travis-ci.org/AdesisNetlife/grunt-jade-i18n/jobs/51218234

**Comment by 7wonders** [comment]
Yes, you are right. Copied the error directory contents to a new project and everything ran as expected. 

Strange that in my own project it still fails with 'No "contrib-jade" targets found. Warning: Task "contrib-jade" failed.' even after full clean and reinstall etc etc. Will do some more investigating.

Here was the expected result from the error example you added. 

```
Running "contrib-jade:templates-es_ES" (contrib-jade) task
Verifying property contrib-jade.templates-es_ES exists in config...OK
Files: views/index.jade -> public/es_ES/index.html
Options: namespace="JST", separator="\n\n", amd=false, i18n={"locales":"locales/*.json","namespace":"$i18n"}, pretty, data={"hello":{"world":"Hola Mundo"},"$i18n":{"hello":{"world":"Hola Mundo"}},"$localeName":"es_ES"}
Reading views/index.jade...OK
Writing public/es_ES/index.html...OK
File public/es_ES/index.html created.
>> 1 file created.

Done, without errors.
```

**Comment by h2non** [comment]
Great! Thank you for reporting

**Comment by prisis** [comment]
I have the same error ...
~~~json
jade: {
			dist: {
				options: {
					i18n: {
						locales: 'locales/*.json',
						namespace: '$i18n',
						localeExtension: true
					},
					pretty: true
				},
				files: [{
					cwd: 'src/jade',
					expand: true,
					src: '*.jade',
					dest: 'dist',
					ext: '.html'
				}]
			}
		},
~~~
